[package]
name = "cephalopod_core"
version = "0.1.0"
edition = "2021"

[dependencies]
base32 = "0.5.1"
base64 = { version = "0.22.1", default-features = false, features = ["std"] }
bumpalo = { version = "3.16.0", default-features = false }
ciborium-io = "0.2.2"
ciborium-ll = "0.2.2"
egui_json_tree = "0.9.0"
serde_json = { version = "1.0.134", default-features = false, features = ["preserve_order", "std"] }
sha2 = "0.10.8"
thiserror = "2.0.9"

[dev-dependencies]
anyhow = "1.0.95"
clap = { version = "4.5.23", features = ["derive"] }
hex = "0.4.3"
leb128 = "0.2.5"
proptest = { version = "1.6.0", default-features = false, features = ["std", "timeout"] }

[[examples.bin]]

name = "show_car"
