(library
 (name cephalopod_dasl)
 (public_name cephalopod.dasl)
 (synopsis "dasl.ing for cephalopod")
 (preprocess
  (pps ppx_deriving.std ppx_deriving_yojson))
 (flags :standard -open Cephalopod_common)
 (libraries
  cephalopod_common
  cephalopod.leb128
  containers
  base32
  yojson
  digestif))
